# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 811a4d0d87acaa3ca5c531172e89b6db8a804a1cac4cb8cbab200a845b38d5c674200f8f741c22f68f6f2954b63fd0789859f9131d1e06879a347e2f0672492a

test:
  secret_key_base: cb80d55035bd34f8d364902d180bc56eff13eb406ae7ed2e715ef11beb83bcc4bced1c8973c93b9f195634beb72b43f14a2f9d34d3c9da340e7e4f43389fda91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
